### ISSUE TITLE
Issue with status and version of the server

### ISSUE THREAD

**Issue by ParsecTraveler** [Dinnerbone/mcstatus#102]
Hi!
At first:
Pretty cool program you got there!

Now the problem:
I created a status  object with "status = server.status()" and stuff like status.players.max works fine. But if I want to get the version of the server with status.version the string is empty, it just shows nothing at all. Using the command line version 1.16.4 is shown. Now is there something I'm doing wrong or is there a problem on your side?

**Comment by Iapetus-11** [comment]
Could you give us both the command you used, and the rest of your code?

**Comment by ParsecTraveler** [comment]
Okay, I fixed the problem myself :). The "dir()" method mentioned in an other issue was pretty useful.
Thanks anyways.

**Comment by kevinkjt2000** [comment]
I’m glad it could help! Issues/questions for a specific python project isn’t really meant for teaching python tricks like `dir`, but I’ve started dropping that knowledge since we each started as a python newbie at some point.
