### ISSUE TITLE
Bedrock support

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [Dinnerbone/mcstatus#103]
Would it be in-scope for this project to support Bedrock Edition servers?

https://wiki.vg/Bedrock_Protocol

**Comment by kevinkjt2000** [comment]
I'd be open to accepting PRs for supporting the Bedrock protocol.

**Comment by Iapetus-11** [comment]
PR #104 adds this!

**Comment by kevinkjt2000** [comment]
Released with 5.1.0
