### ISSUE TITLE
Re-evaluate supported python versions

### ISSUE THREAD

**Issue by kevinkjt2000** [Dinnerbone/mcstatus#105]
One of the dependencies has dropped support for 3.5 (as mentioned in #104). Time to re-evaluate whether claiming support for python3.5 is worth it or not. May as well add 3.9 to the supported list too. If support is still necessary for 3.5, the dependency will have to be updated or replaced.

**Comment by Iapetus-11** [comment]
The dependency that I was talking about would only be a dependency for an async way to check the status of a Bedrock Edition server, sorry if I caused any confusion.

**Comment by kevinkjt2000** [comment]
Still python 3.5 is already past EOL, so I plan to re-evaluate whether or not to support that going forward.

**Comment by Iapetus-11** [comment]
Also in addition to being able to add async Bedrock Edition support more easily, since the query protocol uses UDP as well (iirc) we would benefit by being able to do that more easily as well.

**Comment by Iapetus-11** [comment]
I contacted the developer of `asyncio-dgram` about if there was a specific reason for not supporting 3.5, and they went and added support for Python 3.5. Relevant issue: https://github.com/jsbronder/asyncio-dgram/issues/6

**Comment by Egorrko** [comment]
Btw dnspython v2.0 requires python => 3.6 and contains async query and resolver
https://dnspython.readthedocs.io/en/latest/async.html
https://pypi.org/project/dnspython/

**Comment by Iapetus-11** [comment]
If it is decided to remove support for Python 3.5 I'd make a PR with async lookup functions that utilize the async resolver.

**Comment by kevinkjt2000** [comment]
3.5 is end of life already; long live python >= 3.6
I’ll raise a PR when I get a moment tomorrow to update Travis job and PyPi metadata. Feel free to ditch 3.5 during testing. Speaking of which, I should probably make a script that runs tests for each version in a local script/tool.
