### ISSUE TITLE
Any more updates planned?

### ISSUE THREAD

**Issue by Articuno1234** [Dinnerbone/mcstatus#106]
Just wanted to know if you were planning to update this again and maybe add more features. Thanks!

**Comment by Iapetus-11** [comment]
This package appears to be constantly updated and maintained. You can see active pull requests [here](https://github.com/Dinnerbone/mcstatus/pulls) and active issues [here](https://github.com/Dinnerbone/mcstatus/issues).

**Comment by kevinkjt2000** [comment]
Recent issues and PRs are definitely the most accurate way to see how this project is doing. There is no “official roadmap” per se.
