### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by kevinkjt2000** [Dinnerbone/mcstatus#109]
Docstrings should be included in various places, especially data-structures returned by top-level `MinecraftServer` functions. https://www.python.org/dev/peps/pep-0257/ 

Keep in mind, it would be nice to auto-generate versioned documention on gh-pages that the readme could link to.

**Comment by Iapetus-11** [comment]
You mentioned you wanted to auto-generate docs from these docstrings, is there a specific type of docstring format you'd like to follow? Perhaps [Sphinx](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html)?

**Comment by kevinkjt2000** [comment]
Sphinx is okay with me :)

**Comment by Iapetus-11** [comment]
Since part of Sphinx docstrings includes typehints, should I add typehints for args and methods outside of the docstrings as well?

**Comment by kevinkjt2000** [comment]
Typehints would probably help out with #95 
I'll take all the volunteering you're willing to offer 😃

**Comment by HealingArcYT** [comment]
Maybe also a more complete usage example?
I had a kind of hard time finding MinecraftServer.status().version.name for example
