### ISSUE TITLE
No servers responding with any information

### ISSUE THREAD

**Issue by FluffyFlounder** [Dinnerbone/mcstatus#112]
("Server did not respond with any information!")
OSError: Server did not respond with any information!
Just for a test, I've tried:
server = MinecraftServer("mc.hypixel.net", 25565)
server = MinecraftServer.lookup("mc.hypixel.net")
server = MinecraftServer("mc.hypixel.net", 25565)
server = MinecraftServer.lookup("mc.hypixel.net", 25565)
I also tried that with the actual IP of the server : 172.65.230.166 as a string

**Comment by Iapetus-11** [comment]
Just tested some of these on my PC using the latest version of mcstatus, and they worked fine. Perhaps you're using an outdated/unsupported version of Python, or an outdated version of mcstatus?

**Comment by FluffyFlounder** [comment]
Can you show me the code you used?
`python --version ` returns 3.9.2
and `pip show mcstatus` returns 5.1.1

**Comment by Iapetus-11** [comment]
```
python3 -V
Python 3.9.1

python3
Python 3.9.1 (default, Feb  6 2021, 06:49:13) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mcstatus import MinecraftServer
>>> MinecraftServer("mc.hypixel.net", 25565)
<mcstatus.server.MinecraftServer object at 0x7fb45e372df0>
>>> MinecraftServer("mc.hypixel.net", 25565).status()
<mcstatus.pinger.PingResponse object at 0x7fb45d8d74c0>
>>> MinecraftServer.lookup("mc.hypixel.net")
<mcstatus.server.MinecraftServer object at 0x7fb45e372df0>
>>> exit()

pip show mcstatus
Name: mcstatus
Version: 5.1.1
...
```

**Comment by kevinkjt2000** [comment]
These all worked on my machine too. Tested with python 3.8.7 and 3.9.1. Make sure there is not a network firewall preventing you from connecting to these servers.

**Comment by kevinkjt2000** [comment]
Closing due to lack of response. Seems like it was an issue related to networking and/or firewalls.

**Comment by alexitx** [comment]
I can confirm this issue when pinging only, not when fetching the status. It works fine on vanilla and fabric servers, as well as on Velocity proxies, but not on BungeeCord-based proxies and its forks.

The proxy reports:
```
16:20:34 [INFO] [/127.0.0.1:49208] <-> InitialHandler has pinged
16:20:34 [WARNING] [/127.0.0.1:49208] <-> InitialHandler - IllegalStateException: Not expecting PING
```
While mcstatus raises `OSError: Server did not respond with any information!`

It would be nice to just ping since it's less data and it's faster, unless the problem strictly comes from bungee. The same problem is reported in #92.

**Comment by kevinkjt2000** [comment]
If BungeeCord needs an explicit implementation, let's discuss that in its own issue. #174
