### ISSUE TITLE
sock.connect(sa) socket.timeout: timed out

### ISSUE THREAD

**Issue by malromaihi1056** [Dinnerbone/mcstatus#115]
This error seems to pop up when the server is offline but I want it to print when it's offline and online like 
print("online")

print("offline")
I tried everything I know to change it, it might be a silly mistake by me but can anyone help?

**Comment by kevinkjt2000** [comment]
I don't understand your question. Please share how you are using mcstatus. As a library in your own python script? Or as a command line tool?

**Comment by malromaihi1056** [comment]
> I don't understand your question. Please share how you are using mcstatus. As a library in your own python script? Or as a command line tool?

**Comment by malromaihi1056** [comment]
> I don't understand your question. Please share how you are using mcstatus. As a library in your own python script? Or as a command line tool?

yes its my own tool and I want it  to print "offline" rather than  sock.connect(sa)
socket.timeout: timed out.

**Comment by kevinkjt2000** [comment]
You must be new to Python. I suggest learning how to use try-except, so that you know how to handle the `socket.timeout` exception. https://pythonbasics.org/try-except/
