### ISSUE TITLE
Bedrock?

### ISSUE THREAD

**Issue by rjworks** [Dinnerbone/mcstatus#118]
Does it support bedrock edition? I can't seem to connect due to time out

```
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\arjay\Documents\Personal projects\Python\hybridpe_discord\main.py", line 13, in on_ready
    status = server.status()
  File "C:\Python39\lib\site-packages\mcstatus\server.py", line 97, in status
    connection = TCPSocketConnection((self.host, self.port))
  File "C:\Python39\lib\site-packages\mcstatus\protocol\connection.py", line 131, in __init__
    self.socket = socket.create_connection(addr, timeout=timeout)

```

**Comment by Iapetus-11** [comment]
This does support Bedrock Edition, however it looks like you're using the wrong code to do so.

Something like this might work:
```py
from mcstatus import MinecraftBedrockServer

server = MinecraftBedrockServer.lookup("xenonmc.ml:19133")
status = server.status()
print(status)
```

**Comment by Iapetus-11** [comment]
In addition, it looks like you're using Discord.py, which is async. You do *not* want to use blocking functions with async code. Use the async equivalents of the status functions or a thread pool executor to avoid blocking the event loop and freezing the entire bot.

**Comment by rjworks** [comment]
```
    print("The server has {0} players and replied in {1} ms".format(status.players.online, status.latency))
AttributeError: 'BedrockStatusResponse' object has no attribute 'players'
```

**Comment by Iapetus-11** [comment]
Yes the `BedrockStatusResponse` is different from the other object type. Try `dir(status)` to see what attributes it has!

**Comment by kevinkjt2000** [comment]
I haven't tested if async for Bedrock is broken, but I opened an issue for
async a couple days ago.

**Comment by Iapetus-11** [comment]
I believe it works, as the code was tested by me when I first added it. If that's not the case, I'm happy to fix it!

**Comment by rjworks** [comment]
Is there no list of players?

players_online just gives the number of online players.

**Comment by rjworks** [comment]
I tried using query as shown in the example

`address = "play.hybridpe.me:19132"
    server = MinecraftBedrockServer.lookup(address)
    status = server.status()
    query = server.query()`
but apparently server.query() is an Unresolved attribute reference 'query' for class 'MinecraftBedrockServer'

**Comment by Iapetus-11** [comment]
> I tried using query as shown in the example
> 
> 
> 
> ```
> 
> address = "play.hybridpe.me:19132"
> 
> server = MinecraftBedrockServer.lookup(address)
> 
> status = server.status()
> 
> query = server.query()
> 
> ```
> 
> but apparently server.query() is an Unresolved attribute reference 'query' for class 'MinecraftBedrockServer' 

Bedrock Edition servers are very different from Java Edition servers. There is no query protocol for Bedrock Edition, and the regular server status protocol is different for Bedrock Edition as well.

**Comment by Iapetus-11** [comment]
> Is there no list of players?
> 
> 
> 
> players_online just gives the number of online players.

The Bedrock Server protocol does not support this.

**Comment by rjworks** [comment]
> > Is there no list of players?
> > players_online just gives the number of online players.
> 
> The Bedrock Server protocol does not support this.

I believe it does. Check https://minecraftpocket-servers.com/server/107849/

**Comment by Iapetus-11** [comment]
Let me correct my statement, *vanilla* Minecraft Bedrock Edition servers don't support those features. Software such as NukkitX or Pocketmine do support these features and can be generally treated as Java Edition servers in regard to checking their status.

**Comment by rjworks** [comment]
> Let me correct my statement, _vanilla_ Minecraft Bedrock Edition servers don't support those features. Software such as NukkitX or Pocketmine do support these features and can be generally treated as Java Edition servers in regard to checking their status.

Oh, so I can just use MinecraftServer and not MinecraftBedrockServer?

**Comment by Iapetus-11** [comment]
Well it depends on what type of server you want to get the status of

**Comment by rjworks** [comment]
I ended up using MinecraftServer, and everything works just fine. The server I queried is pocketmine
