### ISSUE TITLE
Print status

### ISSUE THREAD

**Issue by masterhacka** [Dinnerbone/mcstatus#119]
Hi there,

how can I make a python Script which prints out simply Online or Offline?

I can‘t figure it out..

**Comment by kevinkjt2000** [comment]
This issue tracker is not here to teach you Python nor is it for us to write your code for you. You should be able to make a script that prints Online or Offline on your own... If a server is offline, mcstatus functions will raise an appropriate exception that your script can catch. If a server is online, there will be no exceptions, so your script could print "Online".

Hint: you'll want a try-catch block
