### ISSUE TITLE
[Quick Question] How could I use the exact API, but without the module? Explanation below

### ISSUE THREAD

**Issue by QuartzWarrior** [Dinnerbone/mcstatus#121]
How would I use the official Minecraft API? I am using `api.mcsrvstat.us` but want to use the official `mojang` api. I am assuming this module uses it, but can't seem to find it in the code.

   Thanks!

**Comment by Iapetus-11** [comment]
There is a Mojang API, but that is not how this library works, and that API is for something different. This library uses the protocols that Minecraft servers use to communicate to obtain data from them.

If you're looking for an API that can do this you should just use `api.mcsrvstat.us` or something similar as there's no official Mojang API for this.

**Comment by kevinkjt2000** [comment]
Yeah, it's not in the code because that isn't how this library works. Instead checkout https://wiki.vg/Protocol for a very detailed explanation of Minecraft protocols that this library is using.

**Comment by QuartzWarrior** [comment]
Ok, well thanks for the quick response.
