### ISSUE TITLE
async query

### ISSUE THREAD

**Issue by MeRuslan** [Dinnerbone/mcstatus#122]
I'd love to see an async query implemented

**Comment by Iapetus-11** [comment]
I could probably do this Via a ThreadPoolExecutor, but that comes with the drawbacks of using threads. I'll making a PR using a ThreadPoolExecutor for now, and someone who has more knowledge can eventually make a proper async implementation.

**Comment by MeRuslan** [comment]
I'm afraid one would have to make an async version of **UDPSocketConnection** and **ServerQuerier**.
For now I ended up using ThreadPoolExecutor as well.

**Comment by MeRuslan** [comment]
Ok, I've had to implement it myself. 
It turns out the package already has a dependency to work with UDP connections at a high level.
Will post a PR later today.

**Comment by Iapetus-11** [comment]
Oh nice

**Comment by kevinkjt2000** [comment]
Released in 5.2.0! Thanks!
