### ISSUE TITLE
Please add Minecraft Bedrock Edition server ping function.

### ISSUE THREAD

**Issue by minsuho** [Dinnerbone/mcstatus#126]
Please add Minecraft Bedrock Edition server ping function.

**Comment by kevinkjt2000** [comment]
The [Bedrock protocol](https://wiki.vg/Bedrock_Protocol) is different from the [Java Edition protocol](https://wiki.vg/Protocol). Java Edition has a ping function; whereas, Bedrock does not. Bedrock status support was added in #104.
