### ISSUE TITLE
Fetch server-info.png

### ISSUE THREAD

**Issue by regulad** [Dinnerbone/mcstatus#128]
Having the ability to get the server's icon would be very much appreciated.

**Comment by kevinkjt2000** [comment]
This is already supported in the ping response packet: https://github.com/Dinnerbone/mcstatus/blob/a5522934f44f51f995151f2601dba5423926986d/mcstatus/pinger.py#L182-L185
You'll want to access `ping_response.favicon` for the PNG data.

See https://wiki.vg/Server_List_Ping#Response for more info.
