### ISSUE TITLE
Is there documentation? 

### ISSUE THREAD

**Issue by GreenDiscord** [Dinnerbone/mcstatus#131]
If not, Ill ask my question.
How would I get the motd alone?
```py
server.query.motd()
```
Doesn't work, seeing as I have tested.

**Comment by kevinkjt2000** [comment]
`motd` is part of the `.status()` object. Improving documentation is an open issue, but most of the information on what can be gathered is present in the code, on pages like this one https://wiki.vg/Server_List_Ping, and by using Python's built-in `dir` function to list the attributes of an object.
