### ISSUE TITLE
Consider switching to dnspython instead of dnspython3

### ISSUE THREAD

**Issue by MartinHjelmare** [Dinnerbone/mcstatus#132]
## Background

- This library supports an integration in Home Assistant.
- The new pip resolver is more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change

## Problem

- This library requires `dnspython3`, which pins `dnspython` to 1.15.0.

## Solution?

- To avoid incompatibility issues with other libraries that also requires `dnspython` it would be good if `mcstatus` would switch to using `dnspython` directly instead of `dnspython3` and have as forgiving pinning strategy as possible for `dnspython`. According to the readme of `dnspython3`:
  > dnspython3 has been superseded by the regular dnspython kit, which now supports both Python 2 and Python 3

Thanks for your support of Home Assistant!

**Comment by Iapetus-11** [comment]
I considered making this issue as [Poetry](https://python-poetry.org) also has a strict dependency resolver, and conflicts with the `dnspython3` dependency this library requires was causing issues for me. I'd also appreciate it if it was switched!

In addition, the newer versions of dnspython support async resolving. The current `lookup()` method of `MinecraftServer` is not async, so it would be benificial for some people to have an `async_lookup()` method using the newer capabilities of dnspython.
