### ISSUE TITLE
If server is off it times out

### ISSUE THREAD

**Issue by 9ny4** [Dinnerbone/mcstatus#135]
How can i check if the sever is off? if status = server.status() it breaks the rest of the code so it wont get further

**Comment by Iapetus-11** [comment]
Learn basic Python and how exceptions work. "it breaks the rest of the code" because it raises an exception signifying that the server isn't on, you need to catch that exception and handle it properly. https://docs.python.org/3/tutorial/errors.html

**Comment by kevinkjt2000** [comment]
I'm going to open an issue about better documentation since that could explain exception handling to the masses.
