### ISSUE TITLE
Cyrillic characters in names shown incorrectly

### ISSUE THREAD

**Issue by ghost** [Dinnerbone/mcstatus#138]
Hello! I have a very specific problem, when doing query if any of my players have cyrillic letters in their names, those are shown incorrectly. I believe, it is something to do with ASCII encoding and not UTF-8. For example, 'тест' becomes 'B5AB'.

**Comment by kevinkjt2000** [comment]
Does the fix proposed in #99 work for you?

Minecraft uses ISO 8859-1, not UTF-8. I'll add this to my list of things to document in #136.

**Comment by kevinkjt2000** [comment]
It's possible that they are using offline accounts? Or maybe new Microsoft accounts are able to do this?
https://help.minecraft.net/hc/en-us/articles/360050865492-Minecraft-Java-Edition-Account-Migration-FAQ?ref=launcher

Either way, what I commented earlier fixed the issue for Korean characters, so it should probably work for Cryllic characters too. Minecraft has a lot of translations, so it is not surprising to me to see that characters other than `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_` are supported.

**Comment by kevinkjt2000** [comment]
The OP's account appears to have been deleted and I'm tracking the documentation task in #136, so I'm going to close this issue.
