### ISSUE TITLE
Refactor duplicate retry handling code

### ISSUE THREAD

**Issue by kevinkjt2000** [Dinnerbone/mcstatus#139]
There are several places where code looks like this:

```python
        exception_to_raise_after_giving_up: BaseException
        for _ in range(tries):
            try:
                pinger = ServerPinger(connection, host=self.host, port=self.port, **kwargs)
                pinger.handshake()
                return pinger.test_ping()
            except BaseException as e:
                exception_to_raise_after_giving_up = e
        else:
            raise exception_to_raise_after_giving_up
```

The retry logic should be moved into a function or decorator that accepts the code to run in the try block and returns the same as what the try block returns. Additionally, this new retry refactoring must be able to support async try blocks too by properly waiting on them to finish.

**Comment by CoolCat467** [comment]
```
def try_x_times(times:int=3):
    '''Return a wraper that will attempt to run the function it wraps x times. If it fails the x th time, exception is allowed to go uncaught.'''
    def try_wraper(function):
        'Wrapper for given function to try times before exit.'
        @_wraps(function)
        def try_function_wraper(*args, **kwargs):
            'Call a function with given arguments, raise exception on failure more than x times.'
            exception = None
            for attempt in range(times):
                try:
                    return function(*args, **kwargs)
                except Exception as e:
                    exception = e
            raise exception
        return try_function_wraper
    return try_wraper
```

**Comment by ItsDrike** [comment]
> ```python
> def try_x_times(times:int=3):
>     '''Return a wraper that will attempt to run the function it wraps x times. If it fails the x th time, exception is allowed to go uncaught.'''
>     def try_wraper(function):
>         'Wrapper for given function to try times before exit.'
>         @_wraps(function)
>         def try_function_wraper(*args, **kwargs):
>             'Call a function with given arguments, raise exception on failure more than x times.'
>             exception = None
>             for attempt in range(times):
>                 try:
>                     return function(*args, **kwargs)
>                 except Exception as e:
>                     exception = e
>             raise exception
>         return try_function_wraper
>     return try_wraper
> ```

Initially, I was thinking of something similar however there is a problem which is that most of these functions get the number of tries as an argument, which means we can't access it from a decorator
```py
@try_times(tries)  # we don't have `tries` here
def random_function(tries: int = 3, *a, **kw):
    ...
```

I'd like to work on this, but I'd first want to clarify how should this be handled, should we simply assume that `tries` will always be n-th argument of all functions and just get it in the decorator with `args[n]`, or should we pop it from kwargs or alternatively, should we completely abolish the structure of receiving it as a function argument and keep it static in the decorator argument, perhaps from a constant stored somewhere?

**Comment by ItsDrike** [comment]
Any follow-ups on this? I'd like to implement this but I'm still waiting for decision about how exactly should this be handled, in the post above, I've mentioned some possibilities, but some of them would break backwards-compatibility, and those that wouldn't can be a bit messy to implement.

**Comment by CoolCat467** [comment]
Why would one need to change the number of tries for only one of the functions? Why not have a global tries count that could be changed if needed?

**Comment by Iapetus-11** [comment]
> Why would one need to change the number of tries for only one of the functions? Why not have a global tries count that could be changed if needed?

Because global variables are messy, and people might want different retry counts for different functions.

**Comment by Iapetus-11** [comment]
> Why would one need to change the number of tries for only one of the functions? Why not have a global tries count that could be changed if needed?

Because global variables are messy, and people might want different retry counts for different functions.

**Comment by kevinkjt2000** [comment]
The functions don't need to have a `tries` argument, but can still be made to be backwards compatible with a decorator. Here's what I was imagining when I first posted the issue:

```
import functools


def retry(tries):
    def outer(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            wrapped_tries = kwargs.pop("tries", tries)
            exception = None
            for attempt in range(wrapped_tries):
                try:
                    return func(*args, **kwargs)
                except Exception as e:
                    exception = e
            raise exception

        return wrapper

    return outer


@retry(tries=5)
def failing_function(counter):
    counter[0] += 1
    print(counter[0])
    if counter[0] != 10 and counter[0] != 15:
        raise Exception("I'm a failure")


def main():
    counter = [0]
    failing_function(counter, tries=10)
    assert counter[0] == 10
    failing_function(counter)
    assert counter[0] == 15


if __name__ == "__main__":
    main()
```

Supporting async would involve checking if the function is a co-routine and running the function to completion in an event loop? I'm not sure on that.

**Comment by ItsDrike** [comment]
> The functions don't need to have a `tries` argument, but can still be made to be backwards compatible with a decorator

Sounds good! 

I just wanted to note that getting `tries` from kwargs in the wrapped decorator function will work nicely, though it **won't ensure complete backwards compatibility!** This is because `tries` will now need to be a keyword-only parameter, so if anyone was calling `foo(5)` instead of `foo(tries=5)` the code will stop working after an implementation like this is released.

I don't think this is a huge issue and I love this method of solving the problem, `tries` is something that makes sense to be keyword-only anyway since it would be very unclear on what it's doing if it was used as something positional so I don't think this minor backwards compatibility breakage is a huge issue. Even if someone did encounter it, it's very simple to fix and it will make that code cleaner as a benefit. 

I just wanted to mention this here just in case someone encounters it and stumbles on this issue, this is the reason why.

**Comment by kevinkjt2000** [comment]
`tries` could be conditionally grabbed from the positional `*args` if we cared about being backward compatible for this parameter. Of course, that would involve some introspection to figure out which index `tries` is located in the `*args` list. But, since I also agree with it being keyword-only, I'll bump the major version and mention the breakage on that release tag when it happens. No need to go through that much trouble for this pattern cleanup 😄
