### ISSUE TITLE
Test Connection test expects impossible values from a proper varint implementation

### ISSUE THREAD

**Issue by CoolCat467** [Dinnerbone/mcstatus#143]
`test_readBigVarInt` function's assert statement thinks varints should be able to read the value 'FFFFFFFF7F' as 34359738367. This is not correct, as 34359738367 (2 ** 35 - 1) is impossible for proper varints to return, as they can only represent an integer between -2147483648 (2 ** 31) and 2147483647 (2 ** 31 - 1), not 0 to 2 ** 35 - 1

**Comment by kevinkjt2000** [comment]
Resolved as part of #141
