### ISSUE TITLE
HTTPException when using query()

### ISSUE THREAD

**Issue by The12thUnique** [Dinnerbone/mcstatus#152]
I updated to 6.2.0 and I came across this issue where no matter what I do using query() I would get that error everytime, regardless of whether the query port is open or not on the Minecraft Server.

For now I am still on 6.0.0, but this was a weird issue

**Comment by kevinkjt2000** [comment]
Are you certain that the server has the query port unblocked in the firewall and that the query port is enabled in the server.properties?

Can you include the stacktrace please? HTTPException makes no sense...

**Comment by The12thUnique** [comment]
I have tried again and again and can't seem to recreate the issue I had. I tried on both 6.2.0 and 6.4.0.
