### ISSUE TITLE
How to get this?

### ISSUE THREAD

**Issue by start8417** [Dinnerbone/mcstatus#160]
![image](https://user-images.githubusercontent.com/71741383/134009099-1accdf51-c597-4843-a214-4210be7ede36.png)
How to get this?

**Comment by kevinkjt2000** [comment]
See #128
I'll add to my list of things to document

**Comment by kevinkjt2000** [comment]
Oops. My caffeine obviously hasn't kicked in yet this morning. You wanted the MOTD.
That's stored in the status object.

```python
from mcstatus import MinecraftServer

server = MinecraftServer.lookup("example.org:1234")
status = server.status()
print(status.description)
```

It's also included in the query response as `motd`.
