### ISSUE TITLE
Is it possible to use proxy with the mcstatus?

### ISSUE THREAD

**Issue by ROBGUI09** [Dinnerbone/mcstatus#161]
I am using pythonanywhere, which refused connection if you are not using its proxy server, how can i use proxy server with mcstatus?

**Comment by kevinkjt2000** [comment]
Looking at their website, it seems that there is a firewall in place preventing outbound Internet access unless on a paid plan. Are you on the free plan that is limited?

**Comment by kevinkjt2000** [comment]
Fixing Internet access in the environment where mcstatus is run is outside the scope of support that I should be offering.
