### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by Lojstr** [Dinnerbone/mcstatus#163]
add if the server is whitelisted or not in json (or like status_res.whitelist) in the mcstatus/mcstatus/scripts/mcstatus.py line 90+

**Comment by Iapetus-11** [comment]
Whether the server is whitelisted or not is not included in the ping or query status data that the servers send. Adding that one field would require going through part of the login process, and is most likely out of the scope of this library.

**Comment by kevinkjt2000** [comment]
Yes, this would involve more than what the protocol exposes without authenticating.
