### ISSUE TITLE
how do i use this?

### ISSUE THREAD

**Issue by TizoCraft** [Dinnerbone/mcstatus#169]
hey i have absolutely no experience with github/ python and all that programming stuff but i run a server and i am very interested in trying out this thing can anyone help me how to run this? windows or debian 10

**Comment by kevinkjt2000** [comment]
Did you skip reading the README? There are some examples.

Basic Python stuff? That's not what this issue tracker is for. There are a lot of tutorials on the Internet. Installing python, learning how to pip install packages, and being able to run .py files should suffice for you being able to use the README examples.

This issue tracker is also not for teaching GitHub. GitHub has an extensive help section that can get you started https://docs.github.com/en

**Comment by TizoCraft** [comment]
ah thx got it
