### ISSUE TITLE
Using the library asynchronously

### ISSUE THREAD

**Issue by watchingdogs** [Dinnerbone/mcstatus#171]
How would I be able to send async requests using this library? Also a raw output format would be great for non-CLI use also.

**Comment by Iapetus-11** [comment]
There are async methods for nearly every sync method. They are usually prefixed with `async_`, I don't remember all of them but you can easily figure them out if you look into the source of this library. Also there is a raw attribute to some of the status objects, that may be what you want.

**Comment by kevinkjt2000** [comment]
I added another item to the checklist in #136
