### ISSUE TITLE
Change default Timeout

### ISSUE THREAD

**Issue by Salamafet** [Dinnerbone/mcstatus#173]
Hi, 

Thanks for this fantastic module.

Is it possible to change the default request timeout ?
I have try:
`MinecraftServer.lookup("mysuperserver.com", timeout=5)`
and
`server.status(timeout=5)`

But this is an unexpected argument.

Do I need to alter the default timeout of socket module ? And who ?

Thanks for your help

**Comment by kevinkjt2000** [comment]
Propagating a timeout parameter from the high-level functions that call the lower-level network primitives should be possible and is probably a straightforward task for anyone looking to make their first contribution 😃
