### ISSUE TITLE
server.query() Timed Out

### ISSUE THREAD

**Issue by Gu-f** [Dinnerbone/mcstatus#177]
server.ping() and server.status() normal working
but  server.query() timed out.
```
Traceback (most recent call last):  
  File "test.py", line 8, in <module>  
    query = server.query()  
  File "/usr/local/lib/python3.6/site-packages/mcstatus/server.py", line 169, in query  
    raise exception_to_raise_after_giving_up  
  File "/usr/local/lib/python3.6/site-packages/mcstatus/server.py", line 164, in query  
    querier.handshake()  
  File "/usr/local/lib/python3.6/site-packages/mcstatus/querier.py", line 48, in handshake  
    packet = self._read_packet()  
  File "/usr/local/lib/python3.6/site-packages/mcstatus/querier.py", line 41, in _read_packet  
    packet.receive(self.connection.read(self.connection.remaining()))  
  File "/usr/local/lib/python3.6/site-packages/mcstatus/protocol/connection.py", line 240, in read  
    result.extend(self.socket.recvfrom(self.remaining())[0])  
socket.timeout: timed out
```

python3.6
os: centos 7

**Comment by Iapetus-11** [comment]
Query can be enabled/disabled by servers. The server you're trying to use it on most likely has query disabled, hence why it times out.

**Comment by Gu-f** [comment]
Is it the enable-query in the server.properties file?  I set enable-query to true, but it still timed out.  Besides enable-query, it also has query.port, query. port and server-port are the same.   They are both 25565.   Is this normal?

**Comment by Iapetus-11** [comment]
It is in the server.properties file, and it is normal for it to be on the same port. I don't know why it's not working then. What server software and version are you running?

**Comment by Gu-f** [comment]
This server is running Paper version git-Paper-399 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d4318a6 on ver/1.17.1)  
And  
This server is running LoliServer version 1.16.5-a3891ce (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.19)  
Neither of them works.

**Comment by kevinkjt2000** [comment]
Glad you figured it out! Apologies that the documentation still isn’t better yet for this.

This is pinned in issue #164 and mentioned in #136

**Comment by wxydejoy** [comment]
plaease list it in README, thanks

**Comment by wxydejoy** [comment]
@kevinkjt2000

**Comment by ItsDrike** [comment]
> plaease list it in README, thanks

It is mentioned...

https://github.com/Dinnerbone/mcstatus/blob/7fa3c2be25408309c7fc5f3704230deccea8bd6e/README.md?plain=1#L31
