### ISSUE TITLE
MCSTATUS raw

### ISSUE THREAD

**Issue by Aim187** [Dinnerbone/mcstatus#178]
![grafik](https://user-images.githubusercontent.com/65022178/147415689-8abed601-6c75-4fc0-82e6-8809c3b0ec44.png)
![grafik](https://user-images.githubusercontent.com/65022178/147415700-38e5a19c-1de1-4468-8f04-bb091927e13f.png)
Please help me. I dont know what to do!

**Comment by Iapetus-11** [comment]
There is no `modid` key in `status.raw` that i know of. Perhaps you meant `motd` instead. Please check your code before resorting to creating a GitHub issue.

**Comment by kevinkjt2000** [comment]
Please see this comment I made on another issue. It is planned to address this documentation gap in #136 
https://github.com/Dinnerbone/mcstatus/issues/131#issuecomment-849592880
