### ISSUE TITLE
Community Chat?

### ISSUE THREAD

**Issue by kevinkjt2000** [Dinnerbone/mcstatus#193]
Is there interest in having a chat channel where people would be able to ask questions, provide feedback, but-kevin-how-do-i-write-tests-that-you-want and anything else that feels as if it is too informal for GitHub issues?

Discord? Gitter? Something else?

**Comment by b23r0** [comment]
I recommend discord, many communities use him as a discussion tool

**Comment by kevinkjt2000** [comment]
With 3 votes for Discord + my own vote for Discord, I'm going to extrapolate on 4 data points and say Discord is the winner!

Here's an invite https://discord.gg/C2wX7zduxC
