### ISSUE TITLE
Complex Description Styles are lacking test coverage

### ISSUE THREAD

**Issue by kevinkjt2000** [Dinnerbone/mcstatus#195]
We could be missing logic for inserting §r into the parsed descriptions, hard to say without good tests.

**Comment by kevinkjt2000** [comment]
Putting this here so I can find it again later https://minecraft.fandom.com/wiki/Raw_JSON_text_format

**Comment by ItsDrike** [comment]
I was working on that though the PR already got merged so I'll open a new one eventually with some more fixes that should've still been a part of cleanup, though I'm a bit busy now so it may not be that soon.

**Comment by kevinkjt2000** [comment]
That's okay, we're all volunteers here that contribute whenever we feel up
to it. I went ahead with merging because the tests were passing and the PR
was large enough already that I didn't want others to miss out on all the
improvements by not branching from this. I did hold back from making an
official release until we can switch the type checker.

**Comment by kevinkjt2000** [comment]
Gonna close this in favor of #204, where tests will certainly be added.
