### ISSUE TITLE
Update click to 8.0.0

### ISSUE THREAD

**Issue by PerchunPak** [Dinnerbone/mcstatus#198]
![image](https://user-images.githubusercontent.com/68118654/151779681-93c65f91-0104-41aa-986d-fa14a1c06cf2.png)
Also, it would be nice, if you just update all dependencies.

**Comment by kevinkjt2000** [comment]
We should be able to relax that requirement on click to not be an exact requirement (==). Given that it is a major version bump and that mcstatus CLI has low test coverage, this could take a bit because I'd like to add tests. I'll give this a look tonight after I'm done with work.

**Comment by kevinkjt2000** [comment]
Should be fixed in 9.0.0-dev2
