### ISSUE TITLE
Implement or Remove Color Codes

### ISSUE THREAD

**Issue by joezimjs** [Dinnerbone/mcstatus#20]
If you use this [tool on your site](https://dinnerbone.com/minecraft/tools/status/) and look up `play.lichcraft.com`, you'll get some interesting text back on what I believe is the MotD:

> §9Lichcraft.com §7§kZZ §b§kiiii§6§lVote §4§lDaily §6§lAt §6§llichcraft.com/vote§b§kiiii §7§kZZ

I believe most of that nonsense is formatting codes. You can see what all the codes mean at the bottom of this file: https://github.com/matty/MC-ServerQuery/blob/master/mc_serverquery.js

**Comment by kevinkjt2000** [comment]
If someone wants to implement something that strips color codes, feel free :)

**Comment by kevinkjt2000** [comment]
#75 Is at least addressing the display of `\xc2\xa7a\xc2\xa7` to be `§a§l`, which as at least more readable.

**Comment by shayypy** [comment]
> If someone wants to implement something that strips color codes, feel free :)

i simply used `re.sub` to get rid of them. i don't see why this wouldn't be just as good as an official integration? 

```python
re.sub(r"(§.)", "", query.motd)
```

**Comment by CoolCat467** [comment]
#22 did nearly exactly this
