### ISSUE TITLE
Wrong type used for argument in ServerQuerier?

### ISSUE THREAD

**Issue by Naoto-Ida** [Dinnerbone/mcstatus#30]
```
MAGIC_PREFIX = bytearray.fromhex("FEFD")
TypeError: fromhex() argument 1 must be unicode, not str
```

What would be the problem?

**Comment by winny-** [comment]
Can you share your interpreter version? `python --version` or `import sys; print(sys.version)`

I can't seem to create the error condition in cPython 2.7 or 3.4.

**Comment by petbadger** [comment]
I get the exact same error in Python 2.6.1.  

Works fine in Python 2.7.6.

**Comment by winny-** [comment]
Looking at the setup.py, 2.6.x isn't supported.

**Comment by petbadger** [comment]
That explains that!  Thanks for clarifying!

**Comment by Naoto-Ida** [comment]
Yes, sorry for not clarifying that.

**Comment by WeeSkilz** [comment]
@Naoto-Ida close issue?

**Comment by Naoto-Ida** [comment]
@WeeSkilz Sorry, I'll close it.
