### ISSUE TITLE
Animated MOTDs result in errors.

### ISSUE THREAD

**Issue by dmptrluke** [Dinnerbone/mcstatus#31]
I know it's not a proper part of the MOTD spec, but a lot of servers now are using "animated" MOTDs. As long as minecraft itself "supports" them, MCStatus should be able to at least get the first frame from an animated MOTD.

**Comment by lukeroge** [comment]
Example case: Mineplex

**Comment by KamranMackey** [comment]
Yeah, I agree with Luke. MCStatus should really be able to handle "animated" MOTDs. Because it really sucks when MCStatus can't handle them.

**Comment by WeeSkilz** [comment]
I think the issue is that the server sends an 'offline' response to the client which is what allows it to edit the message

**Comment by Ryuutei** [comment]
wtf ? keep it simple.

**Comment by PangeaCake** [comment]
@Ryuutei what do you mean..

**Comment by Ryuutei** [comment]
Who knows what will happen with future servers, no need to add burden to mcstatus with weird modded stuff.

**Comment by PangeaCake** [comment]
@Ryuutei but the client accepts them, so this should too. Isn't that what this is for?

**Comment by penne12** [comment]
@PangeaCake Actually, animated motds are a bug in Minecraft, basically when the server responds with a broken version response, Minecraft polls the server again. In more recent versions of Minecraft (past 1.8.4), animated motds do not work, even in Vanilla Minecraft, I suggest this issue to be closed.

**Comment by kevinkjt2000** [comment]
I concur; closing.
