### ISSUE TITLE
server query issue

### ISSUE THREAD

**Issue by ArduinoKid** [Dinnerbone/mcstatus#32]
i am trying to make a python program where i get an email whenever certain people join the server, however when i try to query the server i get this error:

Traceback (most recent call last):
  File "D:\Josh\Desktop\test1.py", line 5, in <module>
    query = server.query()
  File "D:\Programs\python\lib\site-packages\mcstatus\server.py", line 82, in query
    raise exception
  File "D:\Programs\python\lib\site-packages\mcstatus\server.py", line 77, in query
    querier.handshake()
  File "D:\Programs\python\lib\site-packages\mcstatus\querier.py", line 32, in handshake
    packet = self._read_packet()
  File "D:\Programs\python\lib\site-packages\mcstatus\querier.py", line 25, in _read_packet
    packet.receive(self.connection.read(self.connection.remaining()))
  File "D:\Programs\python\lib\site-packages\mcstatus\protocol\connection.py", line 172, in read
    result.extend(self.socket.recvfrom(self.remaining())[0])
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

additional info:
query is enabled in the server.properties
running vanilla minecraft
when using this site http://goo.gl/YRVYIQ i can see who is on the server just fine
i get the error on both my raspberry pi and pc

**Comment by PangeaCake** [comment]
Can you paste your script here or on hastebin.com or something?

**Comment by ArduinoKid** [comment]
Right now i'm just trying to get the query feature to work so im using the code supplied on the main page of the repository.
the code i'm using is below and in its entirety (i removed the ip as i shouldn't be giving it out):

from mcstatus import MinecraftServer
# If you know the host and port, you may skip this and use MinecraftServer("example.org", 1234)
server = MinecraftServer.lookup("the ip goes here")
# 'query' has to be enabled in a servers' server.properties file.
# It may give more information than a ping, such as a full player list or mod information.
query = server.query()
print("The server has the following players online: {0}".format(", ".join(query.players.names)))

**Comment by winny-** [comment]
Try this server: 54.69.165.139 -- it has the query proto enabled and has a dummy client connected.

It works for me using Python 2.7.6 and mcstatus 2.1.

**Comment by ArduinoKid** [comment]
Thanks, it would appear that I set something up wrong in the server properties as the ip winny supplied works great. Thank you all for the help

**Comment by winny-** [comment]
By the way since [1.7 the regular server list ping](http://wiki.vg/Server_List_Ping) (using the `.status()` method) includes a limited list of players connected to the server. This should work on all servers without modifying `servers.properties` to enable the Query proto.

**Comment by ArduinoKid** [comment]
Sorry but i'm rather new to python and as a result i can't get the .status() method of receiving a limited list of names names to work. Would it be possible for someone to leave an example of how to use this method?

**Comment by winny-** [comment]
Sure -- you may want to read the [official python tutorial](https://docs.python.org/2/tutorial/index.html), however.

Run it like this:
```
$ python2 ping_example.py 54.69.165.139
A Minecraft Server (54.69.165.139) v1.8.3 210.007ms 2/20 dummy, blue_calx
```

----

```
#!/usr/bin/env python

from mcstatus.server import MinecraftServer
import sys


def print_status(address):
    server = MinecraftServer(address)
    status = server.status()
    if status.players.sample:
        players_string = ', '.join(p.name for p in status.players.sample)
    else:
        players_string = ''
    print('{0} ({1}) v{2} {3}ms {4}/{5}{6}{7}'.format(
        status.description,
        address,
        status.version.name,
        status.latency,
        status.players.online,
        status.players.max,
        bool(players_string)*' ',  # Only include space if there is data.
        players_string,
    ))


def main():
    for arg in sys.argv[1:]:
        print_status(arg)


if __name__ == '__main__':
    main()
```

**Comment by scriptinator** [comment]
Idk

**Comment by ArduinoKid** [comment]
Really, bringing an old thread back to life by posting a useless comment?

**Comment by Bunkerbewohner** [comment]
I have the same problem. Any solution?

**Comment by kevinkjt2000** [comment]
@Bunkerbewohner Please create your own issue instead of piggybacking off of someone else's.
Locking this conversation.
