### ISSUE TITLE
Error when importing.

### ISSUE THREAD

**Issue by minecrafttechwiz** [Dinnerbone/mcstatus#33]
When I run "from mcstatus  import MinecraftServer", it says:
"ImportError: No module named 'six'"

**Comment by winny-** [comment]
How did you install mcstatus?

**Comment by minecrafttechwiz** [comment]
First of all, I have a Windows 8.
1. Install Python.
2. Download source.
3. Installed by doing: setup.py install
Any other detail, you can request.

**Comment by winny-** [comment]
Can you verify you have the module 'six' installed?

**Comment by minecrafttechwiz** [comment]
How can I do that?

**Comment by minecrafttechwiz** [comment]
Actually, imported all the modules, which were six and dns. Now its doing its thing.
Next time, maybe have the modules included?

**Comment by winny-** [comment]
It turns oun mcstatus's setup.py uses distutils which doesn't check for dependencies. Ideally it should use something like setuptools.

However, in general, you should take a look at pip which is relatively straight forward to install on windows. Then you can install mcstatus and dependencies like this: `pip install mcstatus`
