### ISSUE TITLE
Add simple CLI For checking server status

### ISSUE THREAD

**Issue by audy** [Dinnerbone/mcstatus#36]
I thought it would be useful to add a simple command-line script for checking the status of a server.

Something like:

``` sh
$ mcstatus server 25599

There are 2 users online.
```

**Comment by penne12** [comment]
+1

**Comment by PangeaCake** [comment]
You could write your own fairly easily

**Comment by winny-** [comment]
You might be interested in the example script in issue #32. `python -m mcstatus server [optional-port]` would obviously be nice.

**Comment by audy** [comment]
Awesome. thanks!
