### ISSUE TITLE
Ping server sends duplicate handshakes

### ISSUE THREAD

**Issue by electromatter** [Dinnerbone/mcstatus#37]
9340ab47c10e28414e80d81735bd795b951f7643 Introduces a bug where handshakes are sent multiple times. This is invalid because the handshakes are not lost, as this is a tcp commection, and this  causes an invalid packet to be sent.

**Comment by kevinkjt2000** [comment]
I'm not sure that this matters enough to fix. Retrying network stuff makes sense to me.
