### ISSUE TITLE
Does not work with 1.6.4 or below servers 

### ISSUE THREAD

**Issue by benaubin** [Dinnerbone/mcstatus#38]
Trying to set this up for a group of modded servers I'm developing for. It looks as if I cannot check the status of, or query a 1.6 or below server.

1.7+ Servers work perfectly
1.6 Servers timeout, on both a `.status()`, and a `.query()`
1.5 Servers do not respond to either, resulting in a `IOError`

My test results:

```
Updating Servers...
   - inf.brierie.co
   - dw20.brierie.co
   - horizons.brierie.net
   - departed.brierie.net
   - cloud9.brierie.co
   - mc.brierie.co
   - monster.brierie.co
     - socket.timeout
   - lite3.brierie.net
   - ultimate.brierie.co
     - IOError
   - horizons.brierie.co
     - socket.timeout
   - tw2.brierie.co
     - socket.timeout
   - regrowth.brierie.net
   - sf2.brierie.net
   - skyblock.brierie.co
   - tppi.brierie.co
     - IOError
```

**Comment by penne12** [comment]
It looks the the [old version](https://github.com/Dinnerbone/mcstatus/tree/release-1.0) of this tool, but that seems like it won't be nice to work with, as I'll have to convert the data from that into this format, and I can't install it.

**Comment by kevinkjt2000** [comment]
1.6 was the last version prior to the netty rewrite in 1.7
https://wiki.vg/Protocol_version_numbers
https://twitter.com/dinnerbone/status/384998161074634752?lang=en

I'm going to close this, as I have no intentions of fixing it.  But should a PR show up that implements the old protocol, I would be willing to review that :)
