### ISSUE TITLE
Hiding server player list

### ISSUE THREAD

**Issue by Ionaru** [Dinnerbone/mcstatus#39]
When using the query on my server, I get the message "Unfortunately, this server is hiding their player list.". All the other information loads normally.
How do I un-hide the player list on my server?

Settings in server.properties:
enable-query=true

Minecraft version:
1.7.10

**Comment by PangeaCake** [comment]
Are you using vanilla?

**Comment by Ionaru** [comment]
No, I'm using KCauldron.

**Comment by PangeaCake** [comment]
Then that is probably a bug on their side.

**Comment by Ionaru** [comment]
I had a feeling that was the case, but I found a workaround using Multicraft's API system. Thanks anyway.
