### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by Rudayb23** [Dinnerbone/mcstatus#42]
Whenever I try to run a query based on a minecraft server IP, I keep getting the error: "socket.timeout: timed out"

Here is the code I am using:
`server = MinecraftServer.lookup('mc.charliecraft.com')`
`query = server.query()`
`print("The server has the following players online: {0}".format(", ".join(query.players.names)))`

Here is the exact error I am getting:
```python 
Traceback (most recent call last):
  File "/mcstatus-master/run.py", line 5, in <module>
    query = server.query()
  File "/mcstatus-master/mcstatus/server.py", line 84, in query
    raise exception
  File "/mcstatus-master/mcstatus/server.py", line 79, in query
    querier.handshake()
  File "/mcstatus-master/mcstatus/querier.py", line 32, in handshake
    packet = self._read_packet()
  File "/mcstatus-master/mcstatus/querier.py", line 25, in _read_packet
    packet.receive(self.connection.read(self.connection.remaining()))
  File "/mcstatus-master/mcstatus/protocol/connection.py", line 172, in read
    result.extend(self.socket.recvfrom(self.remaining())[0])
socket.timeout: timed out
```

**Comment by WeeSkilz** [comment]
You should be using server.status()

**Comment by Rudayb23** [comment]
server.status gives me the amount of players, I want the names of the players as well.

**Comment by WeeSkilz** [comment]
Oh, sorry, I see what you're trying to do.

Is the server online?

**Comment by Rudayb23** [comment]
Yes the server is, the server.status() correctly gives me the amount of players online

**Comment by WeeSkilz** [comment]
Ensure `enable-query` is set to true in your server.properties

**Comment by Rudayb23** [comment]
I'm positive it is

**Comment by Rudayb23** [comment]
Server restart fixed the problem. Server had uptime of 4 months
