### ISSUE TITLE
How do I implement this in HTML

### ISSUE THREAD

**Issue by Riprock** [Dinnerbone/mcstatus#45]
IM making a website and I want to have this in but I don't know how to implement this in. Anyone know how?

**Comment by njuaplusplus** [comment]
You can use some python web framework such as
[Django](https://www.djangoproject.com/) or [Flask](http://flask.pocoo.org/)
to build a website and apply mcstatus to your views.

**Comment by ewm2000** [comment]
Ninja I already have a html site setup. Do you know of a turtorial that can explain how i would insert a python element into my html site with DJango?

**Comment by ewm2000** [comment]
I never worked with DJango before so I dont know how to put mcstatus in a website

**Comment by njuaplusplus** [comment]
Actually, Flask is more light-weighted. But I'm more familiar with Django. 
You can learn from the [Django's official tutorial](https://docs.djangoproject.com/en/1.9/intro/tutorial01/).
After you come through the tutorial, you must be able to implement this. You just need to use mcstatus api in your django's app's `views.py`.

**Comment by ewm2000** [comment]
Thank you @njuaplusplus

**Comment by kevinkjt2000** [comment]
Seems that this question is resolved.
