### ISSUE TITLE
not working with MCProtocolLib

### ISSUE THREAD

**Issue by InterVi** [Dinnerbone/mcstatus#54]
connection failed, [this](https://github.com/Dinnerbone/mcstatus/issues/53) error

**Comment by MarkL4YG** [comment]
If you do have the exact same error: Do NOT open a duplicate...  
If not: Do provide more information.

**Comment by InterVi** [comment]
What kind of information? I don't know why is not working. Do not know the protocol of Minecraft. The game client sees the server, mcstatus - no.

**Comment by MarkL4YG** [comment]
Execution environment, version, general context could really help here.
Also if you could link your log we may be able to spot differences to the linked issue.

**Comment by InterVi** [comment]
Manjaro, 1.12, latest mcprotocollib. My debug info:

> io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Packet "StatusQueryPacket" not fully read

**Comment by MarkL4YG** [comment]
In that case you really don't have the same error as the other issue.
> not fully read

Implies that some(tm) content could be read. I will take a peek at the exception later this day.

**Comment by MarkL4YG** [comment]
Can you link the script you're using to make tracing easier for me?

**Comment by kevinkjt2000** [comment]
I'm not sure I understand this issue at all.  @InterVi Please open a new issue with a more descriptive message, unless #56 fixed your issue already.
