### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MinerPL** [Dinnerbone/mcstatus#65]
C:\Users\Dawid\Desktop\do gadania\DiscordBots\MC>pip install mcstatus
Requirement already satisfied: mcstatus in c:\users\dawid\appdata\local\programs
\python\python36-32\lib\site-packages (2.2)
Requirement already satisfied: six in c:\users\dawid\appdata\local\programs\pyth
on\python36-32\lib\site-packages (from mcstatus) (1.11.0)
Requirement already satisfied: Click in c:\users\dawid\appdata\local\programs\py
thon\python36-32\lib\site-packages (from mcstatus) (7.0)
Requirement already satisfied: dnspython3 in c:\users\dawid\appdata\local\progra
ms\python\python36-32\lib\site-packages (from mcstatus) (1.15.0)
Requirement already satisfied: dnspython==1.15.0 in c:\users\dawid\appdata\local
\programs\python\python36-32\lib\site-packages (from dnspython3->mcstatus) (1.15
.0)

**Comment by MarkL4YG** [comment]
``Requirement already satisfied``
I would say: Just start it?

**Comment by TheRockettek** [comment]
Nothing is wrong with this

**Comment by kevinkjt2000** [comment]
Seems that everything is working as intended here.
