### ISSUE TITLE
[Feature Request] Async

### ISSUE THREAD

**Issue by TECHNOFAB11** [Dinnerbone/mcstatus#70]
It would be cool to be able to use this together with asyncio, to be able to gather info about servers for a Discord bot for example :)

**Comment by laundmo** [comment]
i would also like this feature, the current one is just slow

**Comment by kevinkjt2000** [comment]
Pull requests are welcome :smile:

**Comment by TECHNOFAB11** [comment]
So after finally looking at the code again it seems like the only thing that needs a change is the connection stuff (UDP- and TCPConnection and the dns resolver stuff). The rest just needs the async keywords in front of it basically. For the dns resolver [this](https://github.com/saghul/aiodns) could probably be used and the TCP and UDP connection is supported by asyncio itself. 
When i have time i may look into rewriting this to asyncio, should probably do it soon before i forget how the asyncio socket stuff works.

**Comment by kevinkjt2000** [comment]
#94 Is starting work on this. Please check it out and provide feedback if this feature is of interest to you.
