### ISSUE TITLE
Improve error message for socket.timeout during query

### ISSUE THREAD

**Issue by kevinkjt2000** [Dinnerbone/mcstatus#72]
Several issues have been opened that have prompted questions about the socket.timeout stacktrace during query.

#32 #55 #60 #64 #71 and others:
https://github.com/Dinnerbone/mcstatus/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+query+timeout

The documentation needs to mention something to help people avoid this error, and the code could share a link to that documentation instead of the stacktrace.

**Comment by ConnorXploit** [comment]
I have discovered that calling this way we can get all users names:

```
from mcstatus import MinecraftServer

server = MinecraftServer.lookup("localhost:25565")

status = server.status()

usersConnected = [ user['name'] for user in status.raw['players']['sample'] ]

print(usersConnected)
```

**Comment by kevinkjt2000** [comment]
This issue is about query requiring documentation for port forwarding and firewalls. The comment about status being able to show all the users is off-topic

**Comment by ConnorXploit** [comment]
And what type of information should the query return?
Please solve the problems and specify the utility that should be working on it.

**Comment by kevinkjt2000** [comment]
There are 2 protocols that every minecraft server supports, and you seem to have them confused. One of them is the usual 25565 that most people use to play the game with their clients. Within that protocol it's possible to send a carefully crafted set of network packets to get the online list of players, which is what `status` is doing in this project. `query` operates on a completely separate port and exposes different information through a different protocol. You are confusing the two of them. This issue is open to better document that the query port must be allowed in firewalls otherwise people will see a timeout error.

Please find documentation on the 2 protocols here:
Game client/status https://wiki.vg/Protocol
Query https://wiki.vg/Query

**Comment by Leopounet** [comment]
Basically, just add in the error message or in the doc that the query port (25565 by default) has to be opened and allowing UDP traffic (most people only open for TCP).

**Comment by andubadea** [comment]
> 
> 
> I have discovered that calling this way we can get all users names:
> 
> ```
> from mcstatus import MinecraftServer
> 
> server = MinecraftServer.lookup("localhost:25565")
> 
> status = server.status()
> 
> usersConnected = [ user['name'] for user in status.raw['players']['sample'] ]
> 
> print(usersConnected)
> ```

For me this only returns a sample of 12 players. If there are more players on the server, then it seems some names are randomly excluded.

I have the same issue with query timing out. Interestingly, I noticed that query does not time out if the minecraft launcher is open and on the server list screen. What I am guessing is that the server allows queries when it receives a request from the minecraft launcher, so query then works. If I close the minecraft launcher, query stops working within minutes.

**Comment by lohhans** [comment]
> I have discovered that calling this way we can get all users names:
> 
> ```
> from mcstatus import MinecraftServer
> 
> server = MinecraftServer.lookup("localhost:25565")
> 
> status = server.status()
> 
> usersConnected = [ user['name'] for user in status.raw['players']['sample'] ]
> 
> print(usersConnected)
> ```

It worked like a charm! Thks 🥳... In my case, I've improved the code with this:

```python
try:
	query = server.query()
	players = "The server has the following players online: {0}".format(", ".join(query.players.names))
except Exception as e:
	print("ERROR: " + str(e))
	players = "The server has the following players online: " + str([ user['name'] for user in status.raw['players']['sample'] ]).replace("'", "").replace("[", "").replace("]", "")
	pass
```

**Comment by kevinkjt2000** [comment]
Locking conversation as we migrated repos.

There's an identical issue here https://github.com/py-mine/mcstatus/issues/72
