### ISSUE TITLE
Can't get mcstatus to work

### ISSUE THREAD

**Issue by Badbird-5907** [Dinnerbone/mcstatus#76]
I ran pip install mcstatus it went correctly but running `mcstatus ` or running `from mcstatus import MinecraftServer` i get the following errors:
Mcstatus: 
`mcstatus`
`mcstatus: command not found`

Python `from mcstatus import MinecraftServer`:
`Traceback (most recent call last):
  File "bot.py", line 1, in <module>
    from mcstatus import MinecraftServer
ModuleNotFoundError: No module named 'mcstatus'`

Anyone know how to fix this?

**Comment by kevinkjt2000** [comment]
It seems that your `pip` executable is not in the same environment as your `python` exectuable. Try doing `python -m pip install mcstatus` instead.

**Comment by Badbird-5907** [comment]
Ok, thanks
it seems to be working with python2.7 but I am trying to make a discord bot in python 3. If I run the script `python3 bot.py` I still get this error:
 `python3 bot.py `
 `Traceback (most recent call last):
  File "bot.py", line 1, in <module>
    from mcstatus import MinecraftServer
ModuleNotFoundError: No module named 'mcstatus'`

**Comment by kevinkjt2000** [comment]
Then do `python3 -m pip install mcstatus`?

**Comment by kevinkjt2000** [comment]
I'm going to go ahead with closing this, if you need more support with this issue feel free to re-open. I imagine that once you use the correct pip for your python environment that you should see mcstatus be imported without error.

Installing to the correct python environments is something that pip users should understand as a prerequisite before pip installing anything. `python -m pip install` has  been recommended by a few sources https://snarky.ca/why-you-should-use-python-m-pip/ or https://stackoverflow.com/questions/25749621/whats-the-difference-between-pip-install-and-python-m-pip-install or even the official docs https://docs.python.org/3/installing/index.html#basic-usage

Welcome to the complex world of python installations :smile:

**Comment by ThatCoffeeGuy** [comment]
I know this is an old thread, but might worth posting my solution:

I am using zabbix to monitor my server, but it would scream about missing modules just like your error - The solution was that  I had to install mcstatus for root as well, as zabbix is runing its' scripts as root. 

```root@gamekvm1:~# pip3 install mcstatus```

Thank you .

**Comment by kevinkjt2000** [comment]
@ThatCoffeeGuy please don’t revive anything on this repo. This was all migrated to the new repo.
