### ISSUE TITLE
missing full output and other oddities

### ISSUE THREAD

**Issue by roncanepa** [Dinnerbone/mcstatus#78]
I'm using the itzg/minecraft-server docker container that has mcstatus built in.  No matter what I do, I always seem to get the same limited format output and not the more detailed query/json output.

I have enable-query=true set in my `server.properties`

```
# docker exec -it mc /bin/bash
bash-4.4# mcstatus localhost status
localhost:25565 : version=1.15.1 online=1 max=20 motd='Welcome'
bash-4.4# mcstatus localhost query
localhost:25565 : version=1.15.1 online=1 max=20 motd='Welcome'
bash-4.4# mcstatus localhost json
localhost:25565 : version=1.15.1 online=1 max=20 motd='Welcome'
```

Same is true if I do an exec like mentioned in the container docs: `docker exec mc mcstatus localhost status`

port mappings on teh container are standard for server/rcon, respectively:

```
          - "25565:25565"
          - "25575:25575"
```

I'm assuming it's something simple that I'm missing but I can't seem to find it.

**Comment by kevinkjt2000** [comment]
That's definitely not the same mcstatus. I pulled :latest of the docker you mentioned and found mcstatus was this bash script:

```
└─▪ docker run --rm -it --entrypoint bash itzg/minecraft-server@sha256:e31e1d1d84cdd158cfa036a5c1341568b1b63a83e7356b911a93c0f5b9fc487d
bash-4.4# which mcstatus
/usr/local/bin/mcstatus
bash-4.4# cat /usr/local/bin/mcstatus
#!/bin/bash

##### mcstatus shim for mc-monitor
# handles translating calls to
#   mcstatus (host:port) (command)
# where the actual command is ignore, but is typically ping or status

addr="$1"

IFS=':'
read -a parts <<< "${addr}"
if [[ ${#parts[*]} -gt 1 ]]; then
  exec mc-monitor status --host ${parts[0]} --port ${parts[1]}
else
  exec mc-monitor status --host ${parts[0]}
fi
```

I'm going to close this as invalid since they are not the same mcstatus.

You can use mcstatus in your own docker, if you'd like to. I would start with something like this for a `Dockerfile`:

```
FROM python:3.8
RUN pip install mcstatus
ENTRYPOINT mcstatus
```

**Comment by roncanepa** [comment]
Hello and apologies for the delayed response on this.  Also, for taking up your time. I didn't think to check due to the documentation of the container.  Turns out it was switched and never updated:

https://github.com/itzg/docker-minecraft-server/issues/426

Thank you for your time.

**Comment by kevinkjt2000** [comment]
No worries! Sometimes another pair of 👀 is all it takes to spot something.
