### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by JavaSight** [Dinnerbone/mcstatus#82]
Hi!

I use Firefox as my everyday browser. Your server status tool works fine with other browsers, but on Firefox it will show for a split second then turn into this:

<img src="https://javasight.github.io/sneakcdn/issuecdn/mc/staff/dinnerbone/scdn/Screen%20Shot%202020-04-18%20at%208.20.37%20AM.png">

Thank you for all of your hard work with developing this.

--
JavaSight

**Comment by kevinkjt2000** [comment]
This project is only for the Python project know as `mcstatus`. To provide feedback about Dinnerbone's website, you will need to reach out to Dinnerbone directly. The code for that website is not on GitHub anywhere.
