### ISSUE TITLE
ImportError: cannot import name 'MinecraftServer'

### ISSUE THREAD

**Issue by Footsiefat** [Dinnerbone/mcstatus#86]
```
Traceback (most recent call last):
  File "mcstatus.py", line 1, in <module>
    from mcstatus import MinecraftServer
  File "/home/paul/Downloads/mcstatus.py", line 1, in <module>
    from mcstatus import MinecraftServer
ImportError: cannot import name 'MinecraftServer'

```

**Comment by kevinkjt2000** [comment]
You have named your script with the same name as a library. In Python, this causes trouble. Please try renaming "/home/paul/Downloads/mcstatus.py" to something else.

**Comment by Footsiefat** [comment]
Got it working thanks, although calling server.status() does not get the server version that "mcstatus example.com status" gets. How do i get this?

**Comment by kevinkjt2000** [comment]
Have you checked `server.status().raw`?

**Comment by kevinkjt2000** [comment]
Seems as if the questions have been answered. Please open a new issue if there are any further troubles :smiley:
