### ISSUE TITLE
Players.sample only retrieves 12 player names

### ISSUE THREAD

**Issue by RyanL123** [Dinnerbone/mcstatus#88]
Is this intended? When there are more than 12 players online the names seem to be picked at random. Is there any way to increase the sample size? I understand that for larger servers retrieving 1k+ players is not feasible, just wondering if 12 is the intended upper limit.

**Comment by kevinkjt2000** [comment]
This is a limitation of the protocol exposed by the minecraft server. Only 12 names are returned at most. The sample that is received from the server (https://wiki.vg/Server_List_Ping#Response) is not modified by mcstatus:

https://github.com/Dinnerbone/mcstatus/blob/40d12e5175ed63dbf73187caf85a20c18d20c2be/mcstatus/pinger.py#L102-L105

I would imagine that someone would have to mod the server in some way to make it return more than 12. They probably named it "sample" for this reason; it is only a sample of the players that are online.

**Comment by kevinkjt2000** [comment]
There is a server command `/list` that shows all currently connected players https://minecraft.gamepedia.com/Commands/list

Not all servers have the remote console (rcon) feature enabled, but if your server does have that enabled, you could use an rcon library to remotely list what players are online. That is outside the scope of mcstatus though. mcstatus does not aim to be an rcon library. I wish you luck!
