### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by EeveeSnow** [Dinnerbone/mcstatus#97]
I trying make discord bot with this extension and if I try check info about not working server, I get "Exception has occurred: timeout", have any idea how fix this?

Also, this gives only error:
 ```python
status = nowserver.status()
 players = status.players 
```

**Comment by kevinkjt2000** [comment]
There is nothing for mcstatus to fix. It is likely that the machine where you are running this script from cannot reach the server, or that the server is in a bad state, as you already said `not working server`. mcstatus cannot possibly request status from a server that is not responding... This is behavior that is unexpected. In python, exceptional circumstances are caught by try-except blocks. Here is a tutorial if you are unfamiliar https://docs.python.org/3.8/tutorial/errors.html

mcstatus is doing the normal thing here by raising an exception about an error that it encountered. It is up to the user to handle this.

**Comment by EeveeSnow** [comment]
Thank you! This information been very helpful! Now all work correctly.
