### ISSUE TITLE
(question) not a issue

### ISSUE THREAD

**Issue by nonamedev1** [Dinnerbone/mcstatus#98]
does this contact a API to find out the details of the server

**Comment by Iapetus-11** [comment]
No it doesn't. If you're looking for an API which does something similar, I recommend checking out https://mcsrvstat.us/

**Comment by kevinkjt2000** [comment]
API is a bit of a vague term. You might be referring to code that is extendable (such as the Java API), or you might be talking about a typical modern HTTP Rest API. I'm gonna answer yes, but caveat that with, using a network protocol is not thought of as using an API. What this library does is use specific TCP/UDP packets on specific network ports of the server to simulate a player's game client in very limited ways. However, you could think of the python code itself as an API, much like there's the Java API. The python code is handling all the low-level networking stuff while your app's code is concentrating on high-level logic such as getting status back in a dictionary. Most python programmers call these helpful wrappers, that are pip-installable, packages or libraries.
